name: Compile LaTeX

on:
  push:
    branches:
      - main  # or the branch you want to monitor
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up LaTeX Environment
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex  # Replace with your main .tex file
        latexmk_args: -pdf -interaction=nonstopmode -halt-on-error

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: main.pdf  # Replace with the name of your output PDF
